name: pedometer_application
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.11.0
dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.10.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  google_sign_in: ^6.2.1
  firebase_ui_oauth_google: ^2.0.1
  cloud_firestore: ^6.1.3
  image_picker: ^1.2.1
  logger: ^2.6.2
  firebase_storage: ^13.1.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.4
  video_player: ^2.8.2

  geolocator: ^14.0.2
  pedometer: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/run_app_icon.jpg"
  # สำหรับ Android 8.0 ขึ้นไป เพื่อให้ไอคอนดูทันสมัย
  adaptive_icon_background: "#ffffff" 
  adaptive_icon_foreground: "assets/run_app_icon.jpg"


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/emotion/
    - assets/workout/
