// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR9IkFi1gKAey2kx1jYUl1UCJ_QDeJWXM',
    appId: '1:322948964487:web:149956db7130227658d822',
    messagingSenderId: '322948964487',
    projectId: 'pedometer-workout-application',
    authDomain: 'pedometer-workout-application.firebaseapp.com',
    storageBucket: 'pedometer-workout-application.firebasestorage.app',
    measurementId: 'G-LBRJ76TBMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaRpWWw33l4uA4MiRq4TBEqVUX5Sopho8',
    appId: '1:322948964487:android:614e96dffc3819c258d822',
    messagingSenderId: '322948964487',
    projectId: 'pedometer-workout-application',
    storageBucket: 'pedometer-workout-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8aMWkTnu1wxTgE188I--0o2HELf5gNBA',
    appId: '1:322948964487:ios:88563d17841cf9c458d822',
    messagingSenderId: '322948964487',
    projectId: 'pedometer-workout-application',
    storageBucket: 'pedometer-workout-application.firebasestorage.app',
    iosClientId: '322948964487-gorr1r0eg7l8otn3mob82fh3dj5vj76b.apps.googleusercontent.com',
    iosBundleId: 'com.example.pedometerApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8aMWkTnu1wxTgE188I--0o2HELf5gNBA',
    appId: '1:322948964487:ios:88563d17841cf9c458d822',
    messagingSenderId: '322948964487',
    projectId: 'pedometer-workout-application',
    storageBucket: 'pedometer-workout-application.firebasestorage.app',
    iosClientId: '322948964487-gorr1r0eg7l8otn3mob82fh3dj5vj76b.apps.googleusercontent.com',
    iosBundleId: 'com.example.pedometerApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR9IkFi1gKAey2kx1jYUl1UCJ_QDeJWXM',
    appId: '1:322948964487:web:40bac6d8020778ed58d822',
    messagingSenderId: '322948964487',
    projectId: 'pedometer-workout-application',
    authDomain: 'pedometer-workout-application.firebaseapp.com',
    storageBucket: 'pedometer-workout-application.firebasestorage.app',
    measurementId: 'G-XD7SDV77S1',
  );

}